/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author tuannnh
 */
public class FontWindow extends javax.swing.JFrame {

    public JButton getBtnCancel() {
        return btnCancel;
    }

    public JButton getBtnOk() {
        return btnOk;
    }

    public JComboBox<String> getCbboxFont() {
        return cbboxFont;
    }

    public JComboBox<String> getCbboxSize() {
        return cbboxSize;
    }

    public JComboBox<String> getCbboxStyle() {
        return cbboxStyle;
    }


    public JLabel getLblPreview() {
        return lblPreview;
    }

    
    public FontWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbboxFont = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbboxStyle = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbboxSize = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblPreview = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 300));
        setSize(new java.awt.Dimension(500, 300));

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 60));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel3.setLayout(new java.awt.GridLayout(2, 1));

        jLabel2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        jLabel2.setText("  Text Font:");
        jLabel2.setPreferredSize(new java.awt.Dimension(45, 30));
        jPanel3.add(jLabel2);

        cbboxFont.setPreferredSize(new java.awt.Dimension(96, 30));
        cbboxFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbboxFontActionPerformed(evt);
            }
        });
        jPanel3.add(cbboxFont);

        jPanel1.add(jPanel3, java.awt.BorderLayout.WEST);

        jPanel4.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel4.setLayout(new java.awt.GridLayout(2, 1));

        jLabel3.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        jLabel3.setText("  Font Style:");
        jLabel3.setPreferredSize(new java.awt.Dimension(45, 30));
        jPanel4.add(jLabel3);

        cbboxStyle.setPreferredSize(new java.awt.Dimension(96, 30));
        jPanel4.add(cbboxStyle);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel5.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel5.setLayout(new java.awt.GridLayout(2, 1));

        jLabel4.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        jLabel4.setText("  Size:");
        jLabel4.setPreferredSize(new java.awt.Dimension(45, 30));
        jPanel5.add(jLabel4);

        cbboxSize.setEditable(true);
        cbboxSize.setPreferredSize(new java.awt.Dimension(96, 30));
        jPanel5.add(cbboxSize);

        jPanel1.add(jPanel5, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 180));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jLabel1.setText("Preview");
        jLabel1.setPreferredSize(new java.awt.Dimension(65, 30));
        jPanel2.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(81, 150));

        lblPreview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPreview.setText("AaBbCcYyZz");
        lblPreview.setPreferredSize(new java.awt.Dimension(77, 140));
        jScrollPane1.setViewportView(lblPreview);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel6.setPreferredSize(new java.awt.Dimension(500, 60));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOk.setText("OK");
        btnOk.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel6.add(btnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        btnCancel.setText("Cancel");
        btnCancel.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel6.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        getContentPane().add(jPanel6, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbboxFontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbboxFontActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbboxFontActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox<String> cbboxFont;
    private javax.swing.JComboBox<String> cbboxSize;
    private javax.swing.JComboBox<String> cbboxStyle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPreview;
    // End of variables declaration//GEN-END:variables
}
