/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import control.EditControl;
import control.FileControl;
import java.io.File;
import javax.swing.JMenuItem;
import javax.swing.JTextArea;

/**
 *
 * @author tuannnh
 */
public class MainWindow extends javax.swing.JFrame {
    boolean saved = false;
    String textSaved = "";
    File textFile = null;
 
    public MainWindow() {
        initComponents();
        EditControl editControl = new EditControl();
        editControl.control(this);
        FileControl fileControl = new FileControl();
        fileControl.control(this);
        
    }

    public JTextArea getTxtText() {
        return txtText;
    }


    public JMenuItem getMenuChangeFont() {
        return menuChangeFont;
    }


    public JMenuItem getMenuCopy() {
        return menuCopy;
    }


    public JMenuItem getMenuCut() {
        return menuCut;
    }


    public JMenuItem getMenuExit() {
        return menuExit;
    }

    public JMenuItem getMenuFind() {
        return menuFind;
    }


    public JMenuItem getMenuNew() {
        return menuNew;
    }


    public JMenuItem getMenuOpen() {
        return menuOpen;
    }


    public JMenuItem getMenuPaste() {
        return menuPaste;
    }


    public JMenuItem getMenuRedo() {
        return menuRedo;
    }



    public JMenuItem getMenuReplace() {
        return menuReplace;
    }


    public JMenuItem getMenuSave() {
        return menuSave;
    }



    public JMenuItem getMenuSaveAs() {
        return menuSaveAs;
    }



    public JMenuItem getMenuSelectAll() {
        return menuSelectAll;
    }



    public JMenuItem getMenuUndo() {
        return menuUndo;
    }

    public boolean isSaved() {
        return saved;
    }

    public String getTextSaved() {
        return textSaved;
    }

    public void setSaved(boolean saved) {
        this.saved = saved;
    }

    public void setTextSaved(String textSaved) {
        this.textSaved = textSaved;
    }

    public void setTxtText(JTextArea txtText) {
        this.txtText = txtText;
    }

    public File getTextFile() {
        return textFile;
    }

    public void setTextFile(File textFile) {
        this.textFile = textFile;
    }
    
    

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtText = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuNew = new javax.swing.JMenuItem();
        menuOpen = new javax.swing.JMenuItem();
        menuSave = new javax.swing.JMenuItem();
        menuSaveAs = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuSelectAll = new javax.swing.JMenuItem();
        menuCut = new javax.swing.JMenuItem();
        menuCopy = new javax.swing.JMenuItem();
        menuPaste = new javax.swing.JMenuItem();
        menuUndo = new javax.swing.JMenuItem();
        menuRedo = new javax.swing.JMenuItem();
        menuFind = new javax.swing.JMenuItem();
        menuReplace = new javax.swing.JMenuItem();
        menuChangeFont = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));

        txtText.setColumns(20);
        txtText.setRows(5);
        jScrollPane1.setViewportView(txtText);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        menuNew.setText("New");
        jMenu1.add(menuNew);

        menuOpen.setText("Open");
        jMenu1.add(menuOpen);

        menuSave.setText("Save");
        jMenu1.add(menuSave);

        menuSaveAs.setText("SaveAs");
        jMenu1.add(menuSaveAs);

        menuExit.setText("Exit");
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        menuSelectAll.setText("Select All");
        jMenu2.add(menuSelectAll);

        menuCut.setText("Cut");
        jMenu2.add(menuCut);

        menuCopy.setText("Copy");
        jMenu2.add(menuCopy);

        menuPaste.setText("Paste");
        jMenu2.add(menuPaste);

        menuUndo.setText("Undo");
        jMenu2.add(menuUndo);

        menuRedo.setText("Redo");
        jMenu2.add(menuRedo);

        menuFind.setText("Find");
        jMenu2.add(menuFind);

        menuReplace.setText("Replace");
        jMenu2.add(menuReplace);

        menuChangeFont.setText("Change Font");
        jMenu2.add(menuChangeFont);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuChangeFont;
    private javax.swing.JMenuItem menuCopy;
    private javax.swing.JMenuItem menuCut;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuFind;
    private javax.swing.JMenuItem menuNew;
    private javax.swing.JMenuItem menuOpen;
    private javax.swing.JMenuItem menuPaste;
    private javax.swing.JMenuItem menuRedo;
    private javax.swing.JMenuItem menuReplace;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JMenuItem menuSaveAs;
    private javax.swing.JMenuItem menuSelectAll;
    private javax.swing.JMenuItem menuUndo;
    private javax.swing.JTextArea txtText;
    // End of variables declaration//GEN-END:variables
}
